In [2]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Model,Sequential
from tensorflow import math
import numpy 
numpy.random.seed(10)

In [3]:
vocab_size=500
model_dimension=128
LSTM=Sequential()
LSTM.add(layers.Embedding(input_dim=vocab_size,output_dim=model_dimension))
LSTM.add(layers.LSTM(units=model_dimension,return_sequences=True))
LSTM.add(layers.AveragePooling1D())
LSTM.add(layers.Lambda(lambda x:math.l2_normalize(x)))

input1=layers.Input((None,))
input2=layers.Input((None,))

conc=layers.Concatenate(axis=1)((LSTM(input1),LSTM(input2)))

Siamese=Model(inputs=(input1, input2),outputs=conc)
Siamese.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, None)]       0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, None)]       0           []                               
                                                                                                  
 sequential (Sequential)        (None, None, 128)    195584      ['input_1[0][0]',                
                                                                  'input_2[0][0]']                
                                                                                                  
 concatenate (Concatenate)      (None, None, 128)    0           ['sequential[0][0]',         

In [4]:
def show_layers(model, layer_prefix):
    print(f"Total layers: {len(model.layers)}\n")
    for i in range(len(model.layers)):
        print('====')
        print(f'{layer_prefix}_{i}: {model.layers[i]}\n')
        
print('Siamese model')
show_layers(Siamese, "parallel.sublayers")
print("Details of LSTM model:\n")
show_layers(LSTM, "Serial.sublayers")


Siamese model
Total layers: 4

====
parallel.sublayers_0: <keras.engine.input_layer.InputLayer object at 0x0000020251A12D10>

====
parallel.sublayers_1: <keras.engine.input_layer.InputLayer object at 0x0000020253620A50>

====
parallel.sublayers_2: <keras.engine.sequential.Sequential object at 0x0000020253416090>

====
parallel.sublayers_3: <keras.layers.merging.concatenate.Concatenate object at 0x0000020253514790>

Details of LSTM model:

Total layers: 4

====
Serial.sublayers_0: <keras.layers.core.embedding.Embedding object at 0x0000020251C6FAD0>

====
Serial.sublayers_1: <keras.layers.rnn.lstm.LSTM object at 0x00000202386D0950>

====
Serial.sublayers_2: <keras.layers.pooling.average_pooling1d.AveragePooling1D object at 0x0000020251A11410>

====
Serial.sublayers_3: <keras.layers.core.lambda_layer.Lambda object at 0x000002025361B510>



In [5]:
import numpy as np
import tensorflow as tf

In [6]:
v1=np.array([1,2,3],dtype=float)
v2=np.array([1,2,3.5],dtype=float)
print("input")
print(v1)
print(v2)

def consine_similarity(v1,v2):
    numerator=tf.math.reduce_sum(v1*v2)
    denominator=tf.math.sqrt(tf.math.reduce_sum(v1+v2)*tf.math.reduce_sum(v2*v2))
    return  numerator/ denominator

print("output")
print("cosine similarity",cosine_similarity(v1,v2).numpy())

input
[1. 2. 3.]
[1.  2.  3.5]
output


NameError: name 'cosine_similarity' is not defined

In [7]:
v1_1=np.array([1.0,2.0,3.0])
v1_2=np.array([9.0,8.0,7.0])
v1_3=np.array([-1.0,-4.0,-2.0])
v1_4=np.array([1.0,-7.0,2.0])
v1=np.vstack([v1_1,v1_2,v1_3,v1_4])

In [8]:
v2_1=v1_1+np.random.normal([0,2,3])
v2_2=v1_2+np.random.normal([0,2,3])
v2_3=v1_3+np.random.normal([0,2,3])
v2_4=v1_4+np.random.normal([0,2,3])
v2=np.vstack([v2_1,v2_2,v2_3,v2_4])

In [9]:
print(v1)
print(v2)

b=len(v1)
print(b)
print((b==len(v2)))

sim_1=np.zeros([b,b])
# print(sim_1)

for row in range(sim_1.shape[0]):
    for col in range(sim_1.shape[1]):
        sim_1[row, col] = cosine_similarity([v2[row]], [v1[col]]).numpy()
print("Cosine similarity matrix:\n", sim_1)

[[ 1.  2.  3.]
 [ 9.  8.  7.]
 [-1. -4. -2.]
 [ 1. -7.  2.]]
[[ 2.3315865   4.71527897  4.45459971]
 [ 8.99161615 10.62133597  9.27991444]
 [-0.73448841 -1.89145147  1.00429143]
 [ 0.82539979 -4.56697381  6.20303737]]
4
True


NameError: name 'cosine_similarity' is not defined

In [12]:
def norm(x):
    return tf.math.l2_normalize(x,axis=1)

sim_2=tf.linalg.matmul(norm(v2),norm(v1),transpose_b=True)
print(sim_2)

print(np.allclose(sim_1,sim_2))

tf.Tensor(
[[ 0.97420274  0.93625739 -0.95296132 -0.42971059]
 [ 0.92792012  0.99090123 -0.91371176 -0.38073446]
 [-0.17760618 -0.46654642  0.6064348   0.87241441]
 [ 0.35535524  0.13265633  0.14186592  0.79398094]], shape=(4, 4), dtype=float64)
False


In [19]:
sim_hardcoded=np.array([
    [0.9,-0.0,0.3,-0.5],
    [-0.4,0.5,0.1,-0.1],
    [0.3,0.1,-0.4,-0.8],
    [-0.5,-0.2,-0.7,0.0]
])
sim=sim_hardcoded

b=sim_shape[0]
print(sim)
print(sim.shape)

NameError: name 'sim_shape' is not defined

In [20]:
sim_ap=np.diag(sim)
print(np.diag(sim_ap))
sim_an=sim-np.diag(sim_np)
print(sim_an)


[[ 0.9  0.   0.   0. ]
 [ 0.   0.5  0.   0. ]
 [ 0.   0.  -0.4  0. ]
 [ 0.   0.   0.   0. ]]


NameError: name 'sim_np' is not defined

In [21]:
mean_neg=np.sum(sim_an,axis=1,keepdims=True/(b-1))
print(mean_neg)

NameError: name 'sim_an' is not defined

In [ ]:
mask_1=np.identity(b)==1
mask_2=sim_An>sim_ap.reshape(b,1)
mask=mask_1|mask_2
sim_an_masked=np.copy(sim_An)

sim_an_masked[mask]=-2
closest_neg=np.max(sim_an_mask,axis=1,keepdim=True)

In [ ]:
sim_ap=tf.tf.linalg.diag_part(sim)
print(sim_ap)

sim_an=sim-tf.linalg.diag(sim_ap)
print(sim_an)

In [ ]:
mean_neg=tf.math.reduce_sum(sim_an,axis=1)/(b-1)
print(mean_neg)

mask_1=tf.eye(b)==1
mask_2=sim_an>tf.expand_dims(sim_ap,1)
mask=tf.cast(mask_1|mask_2,tf.float64)
sim_an_masked=sim_an-2.0*mask

closest_neg=tf.math.reduce_max(sim_an_masked,axis=1)
print(closet_neg)


In [ ]:
alpha=0.25

l_1=tf.maximum(mean_neg-sim_ap+alpha,0)
print(l_1)

l_2=tf.maximum(closest_neg-sim_ap+alpha,0)
print(l_2)
l_full=l_1+l_2
cost=tf.math.reduce_sum(l_full)

print(l_full)
print(.format(cost))